apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-rc
  
spec:
  selector:
    matchLabels: 
      app: restapi
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx


