---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config-v2
  namespace: default
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
---
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-v2
spec:
  containers:
  - name: test-container
    image: k8s.gcr.io/busybox
    command: ["/bin/sh", "-c", "env"]
    envFrom:
    - configMapRef:
        name: special-config-v2
  restartPolicy: Never
