apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  volumes:
    - name: persister
      persistentVolumeClaim:
        claimName: pvc-test
  containers:
    - name: pvc-pod
      image: nodyd/k8s-ws
      volumeMounts:
        - mountPath: "/data"
          name: persister

