---
# Derived from https://github.com/microservices-demo/microservices-demo
# Please see this repository for the original

apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    name: payment
spec:
  containers:
  - name: payment
    image: weaveworksdemos/payment:0.4.3
    ports:
    - containerPort: 80