apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  containers:
  - name: server
    image: httpd
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs/
      name: source
  - name: sync
    image: alpine/git
    command:
    - "sh"
    - "-c"
    - "git clone https://github.com/gabrielecirulli/2048 . && watch -n 30 git pull"
    workingDir: /source
    volumeMounts:
    - mountPath: /source
      name: source
  volumes:
  - emptyDir: {}
    name: source