apiVersion: apps/v1
kind: Deployment
metadata:
  name: envtest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: envtest
  template:
    metadata:
      labels:
        name: envtest
    spec:
      containers:
      - name: demo
        image: somkiat/demo_node:1.0
        ports:
        - containerPort: 3000
          hostPort: 80
        env:
        - name: LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: language
              key: LANGUAGE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: apikey
              key: API_KEY