---
apiVersion: v1
kind: Pod
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  containers:
  - name: hello-kubernetes
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 8080
