---
apiVersion: v1
data:
  fluentd.conf: |
    <source>
      type tail
      format json
      path /tmp/log/input.log
      tag count.format1
    </source>
    <match **>
      type file
      format json
      path /tmp/log/output.json
    </match>
kind: ConfigMap
metadata:
  name: fluentd-config

