apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: restapi
spec: 
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: restapi
    spec:
      containers:
        - name: nginx-container
          image: nginx
replicas: 3
selector:
  matchLabels: 
    type: restapi


