apiVersion: v1
kind: Service
metadata:
  name: maindb
  labels:
    name: "maindb"
    version: "1.0"
    module: "maindb"
    environment: "development"
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: "maindb"
    version: "1.0"
    module: "maindb"
    environment: "development"
