apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    name: web
    owner: somkiat
    version: "1.0"
    module: WebServer
    environment: development
spec:
  selector:
    name: web
    owner: somkiat
    version: "1.0"
    module: WebServer
    environment: development

  type: NodePort
  ports:
   - port: 8080
     name: http
     targetPort: 8080
     protocol: TCP
