---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-svc
subsets:
  - addresses:
      - ip: 1.2.3.4
    ports:
      - port: 9376
