apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: web
spec:
  selector:
    app: web

  type: NodePort
  ports:
   - port: 8080
     name: http
     targetPort: 8080
     protocol: TCP
     nodePort: 32500
