---
# Derived from https://github.com/microservices-demo/microservices-demo
# Please see this repository for the original

apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:3.6.8-management
    ports:
    - containerPort: 15672
      name: management
    - containerPort: 5672
      name: rabbitmq