apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: hello
          image: somkiat/hello:v2
          ports:
          - name: hello-port
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 30
