# Define 'Secret' to store db-credentials 
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials # Name of the 'Secret'
data:
  username: dXNlcg==  # base64 encoded 'Secret' username
  password: ZGV2ZWxvcA== # base64 encoded 'Secret' password
