---
# Modified from https://github.com/microservices-demo/microservices-demo
# Please see this repository for the original

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-canary
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
      version: 0.2.1
  template:
    metadata:
      labels:
        name: front-end
        version: 0.2.1
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.2.1
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 1000Mi
        env:
        - name: SESSION_REDIS
          value: "true"
        ports:
        - containerPort: 8079
