apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  labels:
    name: pvc-nfs
    environment: development
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      name: pv-nfs
      environment: development
